name: CI for Energy Network Optimization

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: 1.11.2

    - name: Install dependencies
      run: julia --project=. -e 'using Pkg; Pkg.instantiate()'

    - name: Run tests
      run: julia --project=. -e 'using Test; include("test/runtests.jl")'

    - name: Execute optimization
      run: julia main.jl
    
    - name: Debug Project.toml and Manifest.toml
      run: |
        cat Project.toml
        echo "======"
        cat Manifest.toml
